-- MySQL Script generated by MySQL Workbench
-- Tue Mar 26 14:16:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema comprehensive_supermarket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comprehensive_supermarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comprehensive_supermarket` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `comprehensive_supermarket` ;

-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_customers` (
  `pk_customer_id` INT NOT NULL,
  `customer_name` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` INT NULL DEFAULT NULL,
  `account_balance` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pk_customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_employees` (
  `pk_employee_id` INT NOT NULL,
  `job_position` VARCHAR(255) NULL DEFAULT NULL,
  `salary` FLOAT NULL DEFAULT NULL,
  `phone_number` INT NULL DEFAULT NULL,
  `work_schedules` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`pk_employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_expense_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_expense_reports` (
  `pk_expense_report_id` INT NOT NULL,
  `report_type` VARCHAR(255) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `create_time` DATETIME NULL DEFAULT NULL,
  `supply_expense` FLOAT NULL DEFAULT NULL,
  `employee_expense` FLOAT NULL DEFAULT NULL,
  `other_expense` FLOAT NULL DEFAULT NULL,
  `total_expense` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pk_expense_report_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_inventory_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_inventory_reports` (
  `pk_inventory_report_id` INT NOT NULL,
  `report_type` VARCHAR(255) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `create_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`pk_inventory_report_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_products` (
  `pk_product_id` INT NOT NULL,
  `spu_id` VARCHAR(255) NULL DEFAULT NULL,
  `product_unit` VARCHAR(255) NULL DEFAULT NULL,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`pk_product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_product_variants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_product_variants` (
  `pk_product_id` INT NOT NULL,
  `pk_variant_id` INT NOT NULL,
  `sku_id` VARCHAR(255) NULL DEFAULT NULL,
  `variant_sales_name` VARCHAR(255) NULL DEFAULT NULL,
  `variant_unit_price` FLOAT NULL DEFAULT NULL,
  `variant_description` TEXT NULL DEFAULT NULL,
  `warehouse_quantity` FLOAT NULL DEFAULT NULL,
  `shelf_quantity` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pk_product_id`, `pk_variant_id`),
  CONSTRAINT `t_product_variants_ibfk_1`
    FOREIGN KEY (`pk_product_id`)
    REFERENCES `comprehensive_supermarket`.`t_products` (`pk_product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_product_management_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_product_management_records` (
  `pk_management_record_id` INT NOT NULL,
  `management_date` DATE NULL DEFAULT NULL,
  `management_time` TIME NULL DEFAULT NULL,
  `fk_responsible_employee_id` INT NULL DEFAULT NULL,
  `fk_product_id` INT NULL DEFAULT NULL,
  `fk_variant_id` INT NULL DEFAULT NULL,
  `warehouse_change_quantity` FLOAT NULL DEFAULT NULL,
  `shelf_change_quantity` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pk_management_record_id`),
  INDEX `fk_responsible_employee_id` (`fk_responsible_employee_id` ASC) VISIBLE,
  INDEX `fk_product_id` (`fk_product_id` ASC, `fk_variant_id` ASC) VISIBLE,
  CONSTRAINT `product_management_records_ibfk_1`
    FOREIGN KEY (`fk_responsible_employee_id`)
    REFERENCES `comprehensive_supermarket`.`t_employees` (`pk_employee_id`),
  CONSTRAINT `product_management_records_ibfk_2`
    FOREIGN KEY (`fk_product_id` , `fk_variant_id`)
    REFERENCES `comprehensive_supermarket`.`t_product_variants` (`pk_product_id` , `pk_variant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_reduction_promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_reduction_promotions` (
  `pk_promotion_id` INT NOT NULL,
  `threshold_amount` FLOAT NULL DEFAULT NULL,
  `discount_amount` FLOAT NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`pk_promotion_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_sales_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_sales_reports` (
  `pk_sales_report_id` INT NOT NULL,
  `report_type` VARCHAR(255) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `total_sales` FLOAT NULL DEFAULT NULL,
  `total_revenue` FLOAT NULL DEFAULT NULL,
  `create_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`pk_sales_report_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_suppliers` (
  `pk_supplier_id` INT NOT NULL,
  `company_name` VARCHAR(255) NULL DEFAULT NULL,
  `company_address` VARCHAR(255) NULL DEFAULT NULL,
  `company_website` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_supplier_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_supplier_contacts` (
  `pk_contact_id` INT NOT NULL,
  `fk_supplier_id` INT NULL DEFAULT NULL,
  `contact_name` VARCHAR(255) NULL DEFAULT NULL,
  `contact_title` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` INT NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_contact_id`),
  INDEX `fk_supplier_id` (`fk_supplier_id` ASC) VISIBLE,
  CONSTRAINT `t_supplier_contacts_ibfk_1`
    FOREIGN KEY (`fk_supplier_id`)
    REFERENCES `comprehensive_supermarket`.`t_suppliers` (`pk_supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_supply_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_supply_records` (
  `pk_supply_record_id` INT NOT NULL,
  `fk_supply_product_id` INT NULL DEFAULT NULL,
  `fk_supply_variant_id` INT NULL DEFAULT NULL,
  `fk_supplier_id` INT NULL DEFAULT NULL,
  `supply_date` DATE NULL DEFAULT NULL,
  `supply_quantity` FLOAT NULL DEFAULT NULL,
  `total_price` FLOAT NULL DEFAULT NULL,
  `pay_term` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`pk_supply_record_id`),
  INDEX `fk_supply_product_id` (`fk_supply_product_id` ASC, `fk_supply_variant_id` ASC) VISIBLE,
  INDEX `fk_supplier_id` (`fk_supplier_id` ASC) VISIBLE,
  CONSTRAINT `t_supply_records_ibfk_1`
    FOREIGN KEY (`fk_supply_product_id` , `fk_supply_variant_id`)
    REFERENCES `comprehensive_supermarket`.`t_product_variants` (`pk_product_id` , `pk_variant_id`),
  CONSTRAINT `t_supply_records_ibfk_2`
    FOREIGN KEY (`fk_supplier_id`)
    REFERENCES `comprehensive_supermarket`.`t_suppliers` (`pk_supplier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_variant_discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_variant_discounts` (
  `pk_variant_discount_id` INT NOT NULL,
  `fk_discount_product_id` INT NULL DEFAULT NULL,
  `fk_discount_variant_id` INT NULL DEFAULT NULL,
  `variant_discount_rate` FLOAT NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`pk_variant_discount_id`),
  INDEX `fk_discount_product_id` (`fk_discount_product_id` ASC, `fk_discount_variant_id` ASC) VISIBLE,
  CONSTRAINT `t_variant_discounts_ibfk_1`
    FOREIGN KEY (`fk_discount_product_id` , `fk_discount_variant_id`)
    REFERENCES `comprehensive_supermarket`.`t_product_variants` (`pk_product_id` , `pk_variant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_transaction_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_transaction_records` (
  `pk_transaction_id` INT NOT NULL,
  `fk_responsible_employee_id` INT NULL DEFAULT NULL,
  `fk_customer_id` INT NULL DEFAULT NULL,
  `transaction_date` DATE NULL DEFAULT NULL,
  `transaction_time` TIME NULL DEFAULT NULL,
  `transaction_way` VARCHAR(255) NULL DEFAULT NULL,
  `fk_promotion_id` INT NULL DEFAULT NULL,
  `initial_amount` FLOAT NULL DEFAULT NULL,
  `discounted_amount` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pk_transaction_id`),
  INDEX `fk_promotion_id` (`fk_promotion_id` ASC) VISIBLE,
  INDEX `fk_customer_id` (`fk_customer_id` ASC) VISIBLE,
  INDEX `fk_responsible_employee_id` (`fk_responsible_employee_id` ASC) VISIBLE,
  CONSTRAINT `transaction_records_ibfk_1`
    FOREIGN KEY (`fk_promotion_id`)
    REFERENCES `comprehensive_supermarket`.`t_reduction_promotions` (`pk_promotion_id`),
  CONSTRAINT `transaction_records_ibfk_2`
    FOREIGN KEY (`fk_customer_id`)
    REFERENCES `comprehensive_supermarket`.`t_customers` (`pk_customer_id`),
  CONSTRAINT `transaction_records_ibfk_3`
    FOREIGN KEY (`fk_responsible_employee_id`)
    REFERENCES `comprehensive_supermarket`.`t_employees` (`pk_employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comprehensive_supermarket`.`t_transaction_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprehensive_supermarket`.`t_transaction_details` (
  `pk_transaction_id` INT NOT NULL,
  `pk_transaction_detail_id` INT NOT NULL,
  `fk_product_id` INT NULL DEFAULT NULL,
  `fk_variant_id` INT NULL DEFAULT NULL,
  `purchasing_quantity` FLOAT NULL DEFAULT NULL,
  `discounted_total_price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`pk_transaction_id`, `pk_transaction_detail_id`),
  INDEX `fk_product_id` (`fk_product_id` ASC, `fk_variant_id` ASC) VISIBLE,
  CONSTRAINT `transaction_details_ibfk_1`
    FOREIGN KEY (`pk_transaction_id`)
    REFERENCES `comprehensive_supermarket`.`t_transaction_records` (`pk_transaction_id`),
  CONSTRAINT `transaction_details_ibfk_2`
    FOREIGN KEY (`fk_product_id` , `fk_variant_id`)
    REFERENCES `comprehensive_supermarket`.`t_product_variants` (`pk_product_id` , `pk_variant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
